 redis:
     container_name: task-redis
     image: redis:4.0
     ports:
       - "6379:6379"
 zookeeper:
   container_name: task-zookeeper
   image: zookeeper:3.4.11
   ports:
      - "2181:2181"

 kafka:
   container_name: task-kafka
   image: wurstmeister/kafka
   links:
       - zookeeper:zk
   ports:
       - "9092:9092"
   environment:
       KAFKA_ADVERTISED_HOST_NAME: localhost
       KAFKA_ADVERTISED_PORT: "9092"
       KAFKA_ZOOKEEPER_CONNECT: zk:2181

 mysql:
  container_name: task-mysql
  image: mysql:5.6.23
  ports:
    - "33061:3306"
  environment:
     TZ : "Asia/Shanghai"
     MYSQL_ROOT_PASSWORD: 123456
     MYSQL_DATABASE: db_task
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


